feat: implement theme changing feature to sync with parent app
Chia-Network/core-registry-cadt-ui pull request #68
Opened 2024-07-30 08:02 UTC by newweborder007

This PR adds support for receiving and applying theme changes broadcasted from the parent application, ensuring a consistent look and feel across the entire application suite.

### Changes
- Updated the child app to listen for theme change events from the parent app via window events.
- Implemented logic to dynamically update the app's theme based on changes broadcasted from the parent app.

2024-07-30 20:22 UTC, wwills2 approved these changes

2024-07-30 20:26 UTC, wwills2 requested changes

2024-07-30 20:26 UTC, wwills2 commented on src/components/blocks/LeftNav.js
> +  function notifyParentWhenLeftNavLoaded() {
lets use an arrow function

2024-07-30 20:27 UTC, wwills2 requested changes

2024-07-30 20:27 UTC, wwills2 commented on src/components/blocks/LeftNav.js
> +  function notifyParentWhenLeftNavLoaded() {
lets use an arrow function

2024-08-06 19:00 UTC, wwills2 commented on src/components/blocks/LeftNav.js
> +  function notifyParentWhenLeftNavLoaded() {
please use an arrow function

2024-08-07 15:18 UTC, wwills2 requested changes

2024-08-12 09:39 UTC, newweborder007 commented on src/App.js
> +    <ThemeProvider theme={appStore.customTheme}>
the content of theme.js is the inital state of appStore.customTheme, so it's already working like this.

2024-08-12 10:15 UTC, newweborder007 commented
Hello @wwills2,

Changes have been implemented.
- I removed the conditional rendering of colors, and used default colors.
- Redefined the structure of theme.json in parent app, We can now change any color of theme using parent theme.json.

Note: appStore.theme already have static theme in it's initial state so it's good to go.

2024-08-13 19:35 UTC, wwills2 approved these changes

2024-08-13 23:12 UTC, merged